import { ArrowUpRight, MapPin, Sprout, ScanLine, Compass } from 'lucide-react';
import { ContactCTA, PageIntro } from '@/components/Sections';
import { company } from '@/lib/site';

export default function AboutPage() {
  return <>
    <PageIntro label="ABOUT BHARATGOAI" title={<>An Indian perspective.<br /><span className="serif">A builder’s mindset.</span></>}><p>We’re an India-based AI company exploring how language models and thoughtful engineering can become useful, practical technology.</p></PageIntro>
    <section className="container about-story"><div className="story-title"><span className="eyebrow">WHY WE BUILD</span><h2>Start with context.<br /><span className="serif">Build with intent.</span></h2></div><div className="story-copy"><p className="body-large">BharatGoAI was founded in November 2025 in Hyderabad, with a focus on large language models, quantization and AI/ML projects.</p><p>Our mission is to develop useful AI with Indian users and businesses in mind. We’re interested in the full journey: understanding a problem, working with models, exploring efficiency and shaping a practical application.</p><p>We see language and access as engineering questions as much as design questions. Our work begins with that perspective, and grows through experimentation.</p></div></section>
    <section className="container company-facts"><div><span>COMPANY</span><strong>BharatGoAI</strong></div><div><span>FOUNDED</span><strong>November 2025</strong></div><div><span>BASED IN</span><strong>Hyderabad, India</strong></div><div><span>FOCUS</span><strong>LLMs · Quantization · AI/ML</strong></div></section>
    <section className="section-space founder-section"><div className="container founder-grid"><div className="founder-portrait" aria-label="Typographic monogram for Lokesh E"><span className="eyebrow">THE PERSON BEHIND THE WORK</span><span className="founder-monogram">LE<span>·</span></span><div><span>Lokesh E</span><span>Founder & AI/ML Engineer</span></div></div><div className="founder-copy"><p className="eyebrow">MEET THE FOUNDER</p><h2>Lokesh E</h2><p className="founder-role">Founder & AI/ML Engineer</p><p className="body-large">Working where language models meet practical engineering.</p><p>Lokesh’s work focuses on LLM fine-tuning, quantization and deployment. At BharatGoAI, he brings these interests together through language model development and applied AI/ML projects.</p><p>Explore his Hugging Face profile for models and datasets, with details available on each project’s own page.</p><div className="button-row"><a className="button button-dark" href={company.huggingface} target="_blank" rel="noopener noreferrer">Hugging Face <ArrowUpRight size={17} /></a></div></div></div></section>
    <section className="container section-space"><div className="section-heading"><div><p className="eyebrow">THE WAY WE THINK</p><h2>Principles before <span className="serif">promises.</span></h2></div></div><div className="principles-grid">{[{ icon: Compass, title: 'Context matters', text: 'Start with people, language and the problem a model is intended to solve.' }, { icon: ScanLine, title: 'Details matter', text: 'Look closely at quality, resource requirements and the trade-offs in every approach.' }, { icon: Sprout, title: 'Progress takes care', text: 'Build iteratively. Make room for feedback. Describe work at the stage it has actually reached.' }].map(item => <article key={item.title}><item.icon size={28} strokeWidth={1.5} /><h3>{item.title}</h3><p>{item.text}</p></article>)}</div><div className="location-note"><MapPin size={19} /><span>{company.address}</span></div></section><ContactCTA />
  </>;
}
