import { Link } from 'react-router-dom';
import { PageIntro } from '@/components/Sections';
import type { ReactNode } from 'react';
import { site } from '@/config/site';

type Section = { id: string; title: string; content: ReactNode };
function LegalLayout({ type, title, description, sections }: { type: string; title: string; description: string; sections: Section[] }) {
  return <><PageIntro label={type} title={<span className="serif">{title}</span>}><p>{description}</p></PageIntro><div className="container legal-layout"><aside><p className="eyebrow">ON THIS PAGE</p><nav aria-label={`${type} sections`}>{sections.map((section, index) => <a key={section.id} href={`#${section.id}`}>0{index + 1} / {section.title}</a>)}</nav><p className="legal-date">Last updated: {site.contentUpdated}</p></aside><div className="legal-content">{sections.map(section => <section id={section.id} key={section.id}><h2>{section.title}</h2>{section.content}</section>)}<div className="legal-contact"><h3>Have a question?</h3><p>Contact <a href={`mailto:${site.email}`}>{site.email}</a> or visit our <Link to="/contact">contact page</Link>.</p><address>BharatGoAI<br />{site.addressText}</address></div></div></div></>;
}
export function PrivacyPage() {
  const sections: Section[] = [
    { id: 'scope', title: 'About these notes', content: <p>These general privacy notes describe the BharatGoAI informational website and enquiries sent to our business email. They do not describe a separate model service, account system or paid product. Any future service may have its own privacy information.</p> },
    { id: 'information', title: 'Information you share', content: <><p>If you email us, we receive the information you choose to send, such as your name, email address, organisation and message. Please avoid sending sensitive personal information, passwords or confidential datasets in an initial enquiry.</p><p>The contact form prepares a draft in your browser. Form entries are not submitted to a website server or saved in browser storage by this website. When you choose to send the email, your email provider processes it and it reaches our business mailbox.</p></> },
    { id: 'use', title: 'How information is used', content: <p>Enquiry information is used to understand your request, reply to you and continue the conversation where appropriate. Contacting us is not a sign-up for a marketing list.</p> },
    { id: 'providers', title: 'Hosting and external services', content: <><p>Website hosting and email services may process technical information needed to deliver their services, such as IP addresses, request times and email metadata. Their handling of this information also depends on their own policies.</p><p>This website includes links to external profiles on Hugging Face and GitHub. If you follow a link, the destination’s privacy policy applies. This website does not send visitor messages to a model API.</p></> },
    { id: 'cookies', title: 'Cookies and browser storage', content: <p>Optional privacy-friendly analytics are disabled unless configured and you give consent. No analytics script loads before consent. When enabled, your choice is saved in browser storage and can be withdrawn using the footer control. Contact form entries are not saved in browser storage. Your browser, email app and external websites may have their own storage behaviour.</p> },
    { id: 'retention', title: 'Retention and requests', content: <><p>Email correspondence may be retained to handle an enquiry and related follow-up. Retention can depend on the nature of the conversation and applicable obligations; these notes do not promise a fixed retention period or a particular storage location.</p><p>To ask about access, correction or deletion of information you shared, email {site.email}. We may need information to verify the request and identify the relevant correspondence.</p></> },
    { id: 'changes', title: 'Changes to these notes', content: <p>We may update these notes as the website or our work changes. The date on this page identifies the latest update.</p> },
  ];
  return <LegalLayout type="PRIVACY POLICY" title="Privacy, in plain language." description="General notes on this website, the information you choose to share and how to reach us with a privacy question." sections={sections} />;
}
export function TermsPage() {
  const sections: Section[] = [
    { id: 'website', title: 'Using this website', content: <p>This website presents information about BharatGoAI, our research interests and projects. By using the website, you agree to use it lawfully and in accordance with these general terms.</p> },
    { id: 'work-status', title: 'Research and project information', content: <p>Descriptions of work in development express our current focus. They do not promise a release date, a particular capability, performance result or commercial service. Contact us for current project-specific information. A project engagement requires separately agreed terms.</p> },
    { id: 'acceptable-use', title: 'Acceptable use', content: <p>Do not attempt to disrupt the website, gain unauthorised access to systems, impersonate another person or use contact details for spam or unlawful activity. Respect the rights and privacy of other people.</p> },
    { id: 'ownership', title: 'Content and external projects', content: <><p>BharatGoAI branding and original website content belong to BharatGoAI or their respective owners. Contact us if you wish to reuse material beyond what applicable law permits.</p><p>Code, models and datasets linked from this website may have separate licences. Review the licence and documentation on the relevant project page before using them.</p></> },
    { id: 'links', title: 'Links and availability', content: <p>External links are provided for reference. Their content, availability and terms are controlled by the respective providers. We may update or remove website content, and uninterrupted availability is not guaranteed.</p> },
    { id: 'limitations', title: 'General information and responsibility', content: <p>Website information is provided for general understanding and may change. Please assess its suitability for your purpose. To the extent permitted by applicable law, BharatGoAI is not responsible for losses resulting from reliance on general website information or external content. Nothing in these terms excludes rights or responsibilities that cannot lawfully be excluded.</p> },
    { id: 'law', title: 'Governing law and contact', content: <p>These terms are governed by the applicable laws of India. If you have a concern about the website or these terms, please contact {site.email} so that we can discuss it.</p> },
  ];
  return <LegalLayout type="TERMS OF USE" title="A few shared ground rules." description="General terms for exploring the BharatGoAI website and the work we share here." sections={sections} />;
}
