import { ArrowUpRight, Layers3, Cpu, Workflow } from 'lucide-react';
import { Link } from 'react-router-dom';
import { ContactCTA, PageIntro } from '@/components/Sections';

const projects = [
  { id: 'language-models', topic: 'Language models', number: '01', icon: Layers3, title: 'Language models, with Indian context.', label: 'LARGE LANGUAGE MODELS', color: 'warm', description: 'We’re working on language models with the needs of Indian users and businesses in mind. Our focus is on understanding context and exploring how models can be adapted to useful tasks.', problem: 'A language model’s usefulness depends on the language, context and task it encounters. Our work explores that relationship.', areas: ['Language model experimentation', 'Task-focused fine-tuning', 'Context and response evaluation'], audience: 'Developers, researchers and businesses exploring language-based AI.' },
  { id: 'quantization', topic: 'Quantization', number: '02', icon: Cpu, title: 'Make room for more possibility.', label: 'MODEL QUANTIZATION', color: 'sage', description: 'We’re exploring lower-precision model representations and the trade-offs that come with them. The goal is practical efficiency, with attention to the quality of model outputs.', problem: 'Model memory and compute requirements can limit where an application runs. Quantization is one direction for investigating those constraints.', areas: ['Lower-precision model workflows', 'Quality and resource comparisons', 'Deployment-oriented experimentation'], audience: 'Builders investigating model efficiency and hardware constraints.' },
  { id: 'applied-ai', topic: 'AI/ML projects', number: '03', icon: Workflow, title: 'A real problem is a good beginning.', label: 'APPLIED AI & MACHINE LEARNING', color: 'lavender', description: 'We’re building AI/ML projects around practical questions, connecting experiments to application design and deployment considerations.', problem: 'Moving from an idea to a useful AI application requires a clear task, suitable data and a way to assess results.', areas: ['Problem definition and prototyping', 'Model integration experiments', 'Evaluation and deployment planning'], audience: 'Individuals and businesses exploring a specific AI/ML use case.' },
];
export default function ProductsPage() {
  return <><PageIntro label="OUR WORK" title={<>From model to<br /><span className="serif">meaningful application.</span></>}><p>Three connected areas of work. One intention: build AI that is thoughtfully engineered and grounded in a real need.</p></PageIntro><div className="container work-status"><span className="status-pill"><span />In development</span><p>These are our current areas of work. For project-specific availability and details, <Link to="/contact">get in touch</Link>.</p></div><div className="container project-list">{projects.map(project => <section className="project-section" id={project.id} key={project.id}><div className={`project-visual ${project.color}`} aria-hidden="true"><div className="project-visual-top"><span>{project.label}</span><span>{project.number}</span></div><div className={`card-diagram diagram-${project.number}`}>{Array.from({ length: 7 }, (_, index) => <i key={index} />)}</div><project.icon size={36} strokeWidth={1.2} /><span className="visual-caption">BHARATGOAI / WORK IN PROGRESS</span></div><div className="project-copy"><p className="eyebrow">{project.number} / {project.label}</p><h2>{project.title}</h2><p className="body-large">{project.description}</p><h3>The question we’re working on</h3><p>{project.problem}</p><ul className="feature-list">{project.areas.map(area => <li key={area}>{area}</li>)}</ul><p className="audience"><strong>Relevant to</strong> {project.audience}</p><Link className="text-link" to={`/contact?topic=${encodeURIComponent(project.topic)}`}>Discuss this area <ArrowUpRight size={17} /></Link></div></section>)}</div><ContactCTA /></>;
}
