import { ArrowUpRight, ArrowRight } from 'lucide-react';
import { PageIntro, ContactCTA } from '@/components/Sections';
import { company, site } from '@/config/site';
import { Link } from 'react-router-dom';

const questions = [
  { number: '01', title: 'Vision-language adaptation', question: 'How do we adapt models for Indian-context tasks?', text: 'BharatGoAI focuses on India-focused multimodal models that connect vision and language. Our work includes LoRA fine-tuning and GRPO/GSPO-based adaptation for Indian-context tasks, including handwritten and printed document understanding. Indian-language text and task-specific evaluation are part of the same research direction, alongside practical deployment requirements.', tags: ['Language models', 'Fine-tuning', 'Evaluation'] },
  { number: '02', title: 'Model quantization', question: 'How do we approach model quantization?', text: 'Our model quantization work includes INT8, FP8, W4A16 and NVFP4, with deployment through vLLM. We focus on the relationship between model representation, memory use and practical serving. The project collection links to quantized artifacts and identifies the stage of each model or deployment effort.', tags: ['Quantization', 'Model size', 'Output quality'] },
  { number: '03', title: 'Efficient serving with vLLM', question: 'How does research connect to deployment?', text: 'BharatGoAI connects model adaptation and quantization with efficient serving through vLLM. The deployment direction includes accessible hardware and accuracy evaluation across hardware. Model artifacts and deployment work are listed separately so readers can distinguish released quantization projects, research experiments and work that remains in development.', tags: ['Applied ML', 'Prototyping', 'Deployment'] },
];
export default function ResearchPage() {
  return <><PageIntro label="RESEARCH & EXPLORATION" title={<>Good AI starts with<br /><span className="serif">better questions.</span></>}><p>Our research connects India-focused multimodal language models, vision-language adaptation, quantization and efficient serving with vLLM.</p></PageIntro><section className="container research-questions">{questions.map(item => <article key={item.number} className="question-row"><span className="question-number">{item.number}</span><div><p className="eyebrow">{item.title}</p><h2>{item.question}</h2></div><div><p>{item.text}</p><div className="tag-list">{item.tags.map(tag => <span key={tag}>{tag}</span>)}</div></div></article>)}</section><section className="method-section section-space"><div className="container"><div className="section-heading"><div><p className="eyebrow">OUR ENGINEERING PERSPECTIVE</p><h2>From a question<br /><span className="serif">to a considered answer.</span></h2></div><p>A useful framework for thinking about<br className="desktop-break" /> AI/ML projects, from start to finish.</p></div><div className="method-grid">{[{ title: 'Define', text: 'Understand the intended user, the task and the constraints.' }, { title: 'Explore', text: 'Investigate models, data and approaches that fit the problem.' }, { title: 'Evaluate', text: 'Compare outcomes and examine quality and resource trade-offs.' }, { title: 'Refine', text: 'Use what the experiment reveals to shape the next iteration.' }].map((item, i) => <article key={item.title}><div><span>0{i + 1}</span><ArrowRight size={20} /></div><h3>{item.title}</h3><p>{item.text}</p></article>)}</div></div></section><section className="container section-space public-work"><div><p className="eyebrow">FOLLOW THE WORK</p><h2>Explore the<br /><span className="serif">model work.</span></h2><p>Find the founder’s model work on Hugging Face. Refer to individual project pages for their documentation, status and licence.</p></div><div className="profile-links"><a href={company.huggingface} target="_blank" rel="noopener noreferrer"><span className="profile-symbol">HF</span><div><h3>Hugging Face</h3><p>lokeshe09 · Models & datasets</p></div><ArrowUpRight /></a></div></section><section className="container"><p>Research direction by <Link className="text-link" to="/about">{site.founder.name}, {site.founder.jobTitle}</Link>. Explore the <Link className="text-link" to="/products">multimodal model and quantization projects</Link> or <Link className="text-link" to="/contact">discuss research collaboration</Link>.</p></section><ContactCTA /></>;
}
