import { ArrowUpRight, ArrowRight } from 'lucide-react';
import { PageIntro, ContactCTA } from '@/components/Sections';
import { company } from '@/lib/site';

const questions = [
  { number: '01', title: 'Context & language', question: 'What makes a model useful in its intended context?', text: 'Language, domain and task all shape the work. We’re interested in model adaptation and how to evaluate responses against the problem at hand.', tags: ['Language models', 'Fine-tuning', 'Evaluation'] },
  { number: '02', title: 'Efficiency & trade-offs', question: 'How much can change when a model gets smaller?', text: 'Quantization changes how model weights are represented. Our interest is in the balance between resource requirements and useful output quality.', tags: ['Quantization', 'Model size', 'Output quality'] },
  { number: '03', title: 'Experiments & applications', question: 'What does it take to move beyond a prototype?', text: 'A model is one part of a system. We consider data, interfaces, evaluation and deployment constraints as part of the same engineering problem.', tags: ['Applied ML', 'Prototyping', 'Deployment'] },
];
export default function ResearchPage() {
  return <><PageIntro label="RESEARCH & EXPLORATION" title={<>Good AI starts with<br /><span className="serif">better questions.</span></>}><p>Our interests connect language, model efficiency and practical applications. Here’s a closer look at the questions that guide them.</p></PageIntro><section className="container research-questions">{questions.map(item => <article key={item.number} className="question-row"><span className="question-number">{item.number}</span><div><p className="eyebrow">{item.title}</p><h2>{item.question}</h2></div><div><p>{item.text}</p><div className="tag-list">{item.tags.map(tag => <span key={tag}>{tag}</span>)}</div></div></article>)}</section><section className="method-section section-space"><div className="container"><div className="section-heading"><div><p className="eyebrow">OUR ENGINEERING PERSPECTIVE</p><h2>From a question<br /><span className="serif">to a considered answer.</span></h2></div><p>A useful framework for thinking about<br className="desktop-break" /> AI/ML projects, from start to finish.</p></div><div className="method-grid">{[{ title: 'Define', text: 'Understand the intended user, the task and the constraints.' }, { title: 'Explore', text: 'Investigate models, data and approaches that fit the problem.' }, { title: 'Evaluate', text: 'Compare outcomes and examine quality and resource trade-offs.' }, { title: 'Refine', text: 'Use what the experiment reveals to shape the next iteration.' }].map((item, i) => <article key={item.title}><div><span>0{i + 1}</span><ArrowRight size={20} /></div><h3>{item.title}</h3><p>{item.text}</p></article>)}</div></div></section><section className="container section-space public-work"><div><p className="eyebrow">FOLLOW THE WORK</p><h2>Explore the<br /><span className="serif">model work.</span></h2><p>Find the founder’s model work on Hugging Face. Refer to individual project pages for their documentation, status and licence.</p></div><div className="profile-links"><a href={company.huggingface} target="_blank" rel="noopener noreferrer"><span className="profile-symbol">HF</span><div><h3>Hugging Face</h3><p>lokeshe09 · Models & datasets</p></div><ArrowUpRight /></a></div></section><ContactCTA /></>;
}
